theme: minima

title: My Cloud Blog
author: mapplebliss
email: mapplebliss@github.com
description: > # this means to ignore newlines until "baseurl:"

  Hello! Thank you for visiting my blog! Let's learn together!

# social links
twitter_username: mapplebliss # DO NOT include the @ character, or else the build will fail!
github_username:  mapplebliss # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
